# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'Lily' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

   # Pods for Lily
    pod 'p2.OAuth2', '~> 3.0'
    pod 'Alamofire', '~> 4.0'
    pod 'SwiftyJSON'

    target ‘LilyTests’ do
        pod 'p2.OAuth2', '~> 3.0'
        pod 'Alamofire', '~> 4.0'
        pod 'SwiftyJSON'
    end

end

